export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const CURRENT_CART = "CURRENT_CART";
export const LOAD_ITEMS = "LOAD_ITEMS";
